# ConfigMap is a dictionary of configuration settings
# ConfigMap to keep your application code separate from your configuration.
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  # Configuration values can be set as key-value properties
  MYSQL_DATABASE: technologydb # Which database to use
  MYSQL_DATABASE_URL: jdbc:mysql://mysql/technologydb # Host URL of database
  # Or set as complete file contents (even SQL)  
  initdb.sql: |
    use technologydb;
    CREATE TABLE technology (name VARCHAR(20), framework VARCHAR(20));
    INSERT INTO technology VALUES ('java','springboot');