# Sensitive information in encrypted format
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque # Arbitrary data Base64
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ= # password
  MYSQL_USER: dGVzdHVzZXI=          # testuser
  MYSQL_PASSWORD: dGVzdDEyMw==      # test123