apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootk8sdbconnect
  labels:
    "springboot": k8s
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: springbootk8sdbconnect
  template:
    metadata:
      labels:
        app: springbootk8sdbconnect
    spec:
      containers:
        - image: ishaansolanki6/springbootk8s_v3
          imagePullPolicy: Always
          name: springbootk8sdbconnect
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          livenessProbe:
            tcpSocket:
              port: 8080
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: web-springboot
  labels:
    "springboot": k8s
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: springbootk8sdbconnect
  type: LoadBalancer